module.exports = {
  unprotectedroutes: [
    "/user/admin/login",
    "/user/admin/forgot/password",
    "/user/reset/password",
    "/user/reset/user-password",
    "/user/authentication",
    "/user/VerificationOtp",
    "/user/login",
    "/user/register",
    "/user/verify/account",
    "/user/auto/login",
    "/user/forgot/password",
    "/user/check/email",
    "/user/verify-email",
    "/user/verify-otp",
    "/upload/document",
    "/user/resend-otp",
    "/user/google/signup/login",
    "/category/listing",
    "/user/verify/forgot-otp",
    "/spots/listing",
    "/spots/shapes",
    "/spots/places",
    "/spots/place-detail",
    "/spots/nearby-places",
    "/shapefile/tract",
    "/spots/reviews"

  ],
};
